   name: Pull changed translations from Lokalise
   on:
     workflow_dispatch:
   jobs:
     build:
       runs-on: ubuntu-latest
       steps:
         - name: Checkout Repo
           uses: actions/checkout@v4
           with:
             fetch-depth: 0
         - name: Pull from Lokalise
           uses: lokalise/lokalise-pull-action@v4.0.0
           with:
             api_token: ${{ secrets.LOKALISE_API_TOKEN }}
             project_id: 18122020690d152873da30.32552063
             base_lang: en-GB
             translations_path: translationFiles
             file_format: json
             file_ext: json
             flat_naming: true
             skip_include_tags: true
